name: chatapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  animated_text_kit: ^4.2.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  email_auth: ^1.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_windowmanager: ^0.2.0
  image_picker: ^0.8.5+3
  flutter_easyloading: ^3.0.5
  path: ^1.8.1
  cached_network_image: ^3.2.1
  firebase_storage: ^10.2.17
  path_provider: ^2.0.11
  flutter_secure_storage: ^5.0.2
  firestore_search: ^0.1.9
  firebase_messaging: ^12.0.2
  delayed_display: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
     - family: FiraSans
       fonts:
         - asset: fonts/FiraSans-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
