// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBojkRvI_8qt1-dzOTFIhKlJf3b6E1EtUo',
    appId: '1:235857073674:web:b9069de8c4899e0123f1f3',
    messagingSenderId: '235857073674',
    projectId: 'chatapp-b1ee0',
    authDomain: 'chatapp-b1ee0.firebaseapp.com',
    storageBucket: 'chatapp-b1ee0.appspot.com',
    measurementId: 'G-WFSDDHGCSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXxEpTtk99YbPt2ZQ0lKJE6o0UX50bSY',
    appId: '1:235857073674:android:7120b4941685278b23f1f3',
    messagingSenderId: '235857073674',
    projectId: 'chatapp-b1ee0',
    storageBucket: 'chatapp-b1ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwA6PspPavAfAvff1uNmOuB5IiR9awScY',
    appId: '1:235857073674:ios:59168173811cb31c23f1f3',
    messagingSenderId: '235857073674',
    projectId: 'chatapp-b1ee0',
    storageBucket: 'chatapp-b1ee0.appspot.com',
    iosClientId: '235857073674-dlvedv65t5n5fvv0da8213lj7qi3cpqd.apps.googleusercontent.com',
    iosBundleId: 'com.ajantasilaimachine.chatapp',
  );
}
